version: '3.8'
services:
  web:
    build: ./app
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development

  server:
    build: ./server
    ports:
      - "8080:8000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  python-service:
    build: ./analysis
    volumes:
      - ./analysis:/usr/src/app
      - ./server:/usr/src/server
    env_file:
      - .env
    depends_on:
      - db

volumes:
  pgdata:
